name: MinecartStarter
main: com.roboticoverlord.micro.bukkit.MinecartStarter
version: 1.0
commands:
  minecart:
    description: Spawns a minecart, places player in, and gives it initial momentum.
    usage: /<command>
permissions:
  minecartstarter.can:
    description: allows minecart command to be used;
    default: op